config/routes.rb
Contanko::Application.routes.draw do
  #mount RailsAdmin::Engine => '/dbadmind', as: 'rails_admin'
  require 'sidekiq/web'
  # auth
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
    resources :tankos
  end

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/models/tanko.rb
class Tanko < ActiveRecord::Base

validates :service_name, presence: true,
                    length: { minimum: 5 }

end

app/controllers/tankos_controller.rb
class TankosController < ApplicationController

  def index
    @tankos = Tanko.all
  end

  def new
    @tanko = Tanko.new
  end

  def edit
    @tanko = Tanko.find(params[:id])
  end

  def show
    @tanko = Tanko.find(params[:id])
  end

  def create
    @tanko = Tanko.new(tanko_params)
    if @tanko.save
    redirect_to @tanko
    else
    render'new'
    end
  end

  def update
    @tanko = Tanko.find(params[:id])
    if tanko.update(tanko_params)
      redirect_to @tanko
    else
      render 'edit'
    end
  end
private
  def tanko_params
    params.require(:tanko).permit(:service_name, :description)
  end
end

app/helpers/tankos_helper.rb
module TankosHelper
end

app/views/tankos/index.html.erb
<h1>Tankos</h1>
 
<table class="table table-striped">
  <tr>
    <th>Service Name</th>
    <th>Description</th>
    <td></td>
   <td></td>
  <td></td>
  </tr>
 
  <% @tankos.each do |tanko| %>
    <tr>
      <td><%= tanko.service_name %></td>
      <td><%= tanko.description %></td>
     <td>
          <%= link_to 'View', tanko_path(tanko), :class => 'btn btn-default' %>
      </td><td>    <%= link_to 'Edit', edit_tanko_path(tanko), :class => 'btn btn-default' %>
         </td><td> <%= link_to 'Destroy', tanko_path(tanko), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
        </td> 
   </tr>
  <% end %>
</table>

<p>
<%= link_to new_tanko_path, class: "btn btn-primary" do %>
    <i class="glyphicon glyphicon-plus"></i>  Create new service
<% end %>
</p>

app/views/tankos/new.html.erb
<h1>New Tanko</h1>



<%= form_for :tanko, url: tankos_path do |f| %>

<% if @tanko.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tanko.errors.count, "error") %> prohibited
      </h2>
      <ul>
        <% @tanko.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :service_name %><br>
    <%= f.text_field :service_name %>
  </p>
 
  <p>
    <%= f.label :description%><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
 <i class="glyphicon glyphicon-cloud"></i> Create New Tanko
<% end %>
  </p>
<% end %>
<p>
<%= link_to tankos_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-chevron-left"></i> Back
<% end %>
</p>

app/views/tankos/show.html.erb
<p> 
  <strong>Service:</strong>
  <%= @tanko.service_name %>
</p>
 


<p>
  <strong>Description:</strong>
  <%= @tanko.description %>
</p>